[config]
default_to_workspace = false

[tasks.web]
dependencies = ["compile_wasm", "serve"]

[tasks.compile_wasm]
script = '''
wasm-pack build --out-dir ../../bin/editor/wasm/multithread --target no-modules ./crates/lib/multithread/
cargo build --release --target wasm32-unknown-unknown
wasm-bindgen --out-name app --out-dir crates/bin/editor/wasm --target web target/wasm32-unknown-unknown/release/editor.wasm
'''

[tasks.serve]
script = '''
basic-http-server ./crates/bin/editor/
'''
